<?php

namespace DEUSI\NotifBundle\Repository;

/**
 * UserSUbscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSUbscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
