deusi_notif_home:
    path:    /subscribe
    defaults: { _controller: DEUSINotifBundle:Notification:subscription }
    
deusi_notif_send:
    path:    /send
    defaults: { _controller: DEUSINotifBundle:Notification:sendNotification }
